enum Permissions {
  READ
  WRITE
  LOGIN
  COMMENT
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
  PUBLISHED
  UNPUBLISHED
}

type Author {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  comments: [Comment!]
  posts: [Post!]
  permissions: [Permissions!]
}

type Comment {
  id: ID!
  text: String!
  author: Author!
  post: Post!
}
 
type Post {
  id: ID!
  title: String!
  author: Author!
  comments: [Comment!]
  published: Boolean
}
 
type Query {
  author(id: ID!): Author
  authors(query: String): [Author]
  comment(id: ID!): Comment
  comments(author: String, text: String): [Comment]
  post(id: ID!): Post
  posts(query: String): [Post]
}

type Mutation {
  createAuthor(author: CreateAuthorInput!): Author!
  createComment(comment: CreateCommentInput!): Comment!
  createPost(post: CreatePostInput!): Post!

  deleteAuthor(authorId: String!): Author!
  deleteComment(commentId: String!): Comment!
  deletePost(postId: String!): Post!
  
  updateAuthor(id: String!, data: UpdateAuthorInput!): Author!
  updateComment(id: String!, data: UpdateCommentInput!): Comment!
  updatePost(id: String!, data: UpdatePostInput!): Post!

  publishPost(id: String!): Post!
  unPublishPost(id: String!): Post!
}

type Subscription {
  countdown(from: Int): Int!
  author(by: SubscribeAuthorInput): AuthorSubscriptionPayload
  comment(by: SubscribeCommentInput): CommentSubscriptionPayload
  post(by: SubscribePostInput): PostSubscriptionPayload
}

type AuthorSubscriptionPayload {
  mutation: MutationType!
  data: Author
}

type CommentSubscriptionPayload {
  mutation: MutationType!
  data: Comment
}

type PostSubscriptionPayload {
  mutation: MutationType!
  data: Post
}

input SubscribeAuthorInput {
  email: String
  id: String
}

input SubscribeCommentInput {
  author: String
  post: String
}

input SubscribePostInput {
  author: String
}

input CreateAuthorInput {
  firstName: String!
  lastName: String!
  email: String!
}
input CreateCommentInput {
  authorId: String!
  postId: String!
  text: String!
}
input CreatePostInput {
  authorId: String!
  title: String!
  body: String
  published: Boolean
}

input UpdateAuthorInput {
  firstName: String
  lastName: String
  email: String
}
input UpdateCommentInput {
  authorId: String
  postId: String
  text: String
}
input UpdatePostInput {
  authorId: String
  title: String
  body: String
  published: Boolean
}

schema {
  query: Query
}