enum Permissions {
  READ
  WRITE
  LOGIN
  INTERACT
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
  PUBLISHED
  UNPUBLISHED
}

type Like {
  author: Author!
  post: Post!
}

type Author {
  id: ID!
  email: String!
  handle: String!
  name: String!
  verified: Boolean
  avatar: String!
  banner: String
  bio: String
  link: String
  location: String
  birthday: String
  posts: [Post!]
  permissions: [Permissions!]
  interactions: [Interaction!]
}

type Interaction {
  id: ID!
  author: Author!
  post: Post!
  text: String
  share: Boolean
  like: Boolean
}

type Post {
  id: ID!
  title: String!
  author: Author!
  published: Boolean
  text: String
  media: [String]
  tags: [String]
  interactions: [Interaction!]
}

type Query {
  author(id: ID!): Author
  authors(by: AuthorByInput): [Author]
  interaction(id: ID!): Interaction
  interactions(by: InteractionByInput): [Interaction]
  post(id: ID!): Post
  posts(by: PostByInput): [Post]
}

type Mutation {
  createAuthor(author: CreateAuthorInput!): Author!
  createInteraction(interaction: CreateInteractionInput!): Interaction!
  createPost(post: CreatePostInput!): Post!

  deleteAuthor(authorId: String!): Author!
  deleteInteraction(interactionId: String!): Interaction!
  deletePost(postId: String!): Post!

  updateAuthor(id: String!, data: UpdateAuthorInput!): Author!
  updateInteraction(id: String!, data: UpdateInteractionInput!): Interaction!
  updatePost(id: String!, data: UpdatePostInput!): Post!

  publishPost(id: String!): Post!
  unPublishPost(id: String!): Post!

  verifyAuthor(id: String!): Author!
}

type Subscription {
  countdown(from: Int): Int!
  author(by: AuthorByInput): AuthorSubscriptionPayload
  interaction(by: InteractionByInput): InteractionSubscriptionPayload
  post(by: PostByInput): PostSubscriptionPayload
}

type AuthorSubscriptionPayload {
  mutation: MutationType!
  data: Author
}

type InteractionSubscriptionPayload {
  mutation: MutationType!
  data: Interaction
}

type PostSubscriptionPayload {
  mutation: MutationType!
  data: Post
}

input AuthorByInput {
  email: String
  handle: String
  id: String
}

input InteractionByInput {
  author: String
  post: String
}

input PostByInput {
  author: String
  title: String
}

input CreateAuthorInput {
  name: String!
  handle: String!
  email: String!
  avatar: String
  banner: String
}
input CreateInteractionInput {
  authorId: String!
  postId: String!
  text: String
  like: Boolean
  share: Boolean
}
input CreatePostInput {
  authorId: String!
  title: String!
  body: String
  published: Boolean
}

input UpdateAuthorInput {
  name: String
  email: String
  avatar: String
  banner: String
}
input UpdateInteractionInput {
  authorId: String
  postId: String
  text: String
  like: Boolean
  share: Boolean
}
input UpdatePostInput {
  authorId: String
  title: String
  body: String
  published: Boolean
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
